service: aws-shop-app-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getProductsList:
    handler: handlers.getProductsList
    events:
      - http:
          path: /products
          method: get
  getProductsById:
    handler: handlers.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
